### ISSUE TITLE
Couple of problems/improvements

### ISSUE THREAD

**Issue by tomkuijsten** [Rinsen/WebServer#10]
In RequestContext.SetHeaders there is no check if headerParts has at least 2 items, I've ran into crashes here.

I've increased the ServerContext.MaxClientHeaderSize to 20000 because my headers were to big (I used IE and chrome to do a normal request and it already exceeded the default 8192 size).

**Comment by Rinsen** [comment]
Hi!

The size limit is from when i was running this on older Netduinos so it could for sure be 20000 today.

And the RequestContext.SetHeaders should have a better behavior for sure.

I will commit a change on this as soon as i have made some more testing on the header parsing, thanks for the feedback!

**Comment by Rinsen** [comment]
Do you have any examples on a header that crashes? All valid headers should give at least two parts as far as i can understand the header specs. But i have added some smaller changes that will fix some parsing issues that i have had and I will commit these changes soon.
