### ISSUE TITLE
null reference exception when running the Blink demo page

### ISSUE THREAD

**Issue by aallman** [Rinsen/WebServer#2]
Hello Fredrik,

First of all, I think this is a great project and looks like it will be a big help for many (including me).  Thanks very much for sharing it!

I just ran across your project yesterday and haven't gotten beyond trying the demo on a netduino plus 2 (running 4.3.1.0).  The other pages work just fine but I'm getting this exception when I try the /Blink page:

A first chance exception of type 'System.NullReferenceException' occurred in Rinsen.WebServer.dll
A first chance exception of type 'System.ArgumentOutOfRangeException' occurred in mscorlib.dll
A first chance exception of type 'System.NullReferenceException' occurred in Rinsen.WebServer.dll
A first chance exception of type 'System.NullReferenceException' occurred in Rinsen.WebServer.dll
A first chance exception of type 'System.Exception' occurred in Rinsen.WebServer.dll
Unhandled exception in web server, Message: Exception was thrown: System.NullReferenceException, StackTrace:  Fredde.Web.MicroFramework.FormCollection::AddQueryString
Fredde.Web.MicroFramework.FormCollection::.ctor
Rinsen.WebServer.Controller::GetFormCollection
DemoWeb.BlinkController::Index
System.Reflection.MethodBase::Invoke
Rinsen.WebServer.HttpApplicationHandler::Execute
Rinsen.WebServer.RequestResponseHandler::CreateResponse
Rinsen.WebServer.RequestResponseHandler::ProcessRequest
Rinsen.WebServer.SocketListener::ProcessRequest
Rinsen.WebServer.SocketListener+<>c__DisplayClass1::<ProcessClientRequest>b__0

The thread '<No Name>' (0x8) has exited with code 0 (0x0).
Unhandled exception in web server, Message: Error in error handler , StackTrace:  Rinsen.WebServer.RequestResponseHandler::ProcessRequest
Rinsen.WebServer.SocketListener::ProcessRequest
Rinsen.WebServer.SocketListener+<>c__DisplayClass1::<ProcessClientRequest>b__0

Is there something simple I'm missing?

Thanks!
Andy

**Comment by Rinsen** [comment]
Hi!

I'm glad that you liked it, and thanks for the feedback!

I have committed a change that will solve this issue, it was a null reference from Uri.QueryString when no QueryString was there, but as the design is made it should return an empty string and now it does.

**Comment by Rinsen** [comment]
I think I will give you a chance to get back if it doesn´t solve you're problem :)

**Comment by aallman** [comment]
Works now.

Thanks!!
