### ISSUE TITLE
Question, can I add a controller for the default url (without any /postfix)

### ISSUE THREAD

**Issue by tomkuijsten** [Rinsen/WebServer#6]
Thanks for this lib. It's the most stable and currently active one I found. I love the implementation of routes, saved me a lot of time. Got one question though, can I add a "default" route?

**Comment by Rinsen** [comment]
Thanks!

I have been thinking about adding this feature earlier and I hope that I will have time tomorrow to commit a change that will give you this, I have a working prototype but will need to test this a bit more to make sure it doesn't brake anything.

**Comment by tomkuijsten** [comment]
Cool, thanks for the reply. If I can be of any help, I'm glad to test/code/etc anything.

**Comment by Rinsen** [comment]
I have now added this change, the best help you can give is to test this out and get back if it does not work as expected! The demo web is updated with a default controller and i have added some documentation about this in the project description file.

**Comment by tomkuijsten** [comment]
Very nice thanks. I'll try to test it today.

**Comment by tomkuijsten** [comment]
Just tested it, works like a charm, thanks.
