### ISSUE TITLE
Questions: posting json objects & using angularjs

### ISSUE THREAD

**Issue by aallman** [Rinsen/WebServer#7]
Hello Fredrik,

I'd like to be able to create a simple single page application using angular and D3 on a netduino 2 plus.

These libraries are somewhat large, so I was originally planning on pointing to CDNs.  However, it would be nice if they could be located on an SD card on the device.  If this is supported, is it necessary to create a controller for the routes to the pages or is it based on the file name only?

Also, to get data back and forth between the client and the device, I was going to use json data.  I saw your example that handles the GET, but was wondering how a POST would work.  Does everything in the json object show up in the form collection?

If you are interested (and I'm able to get my project working), I'd be happy to share the results as an example for the project.

Thanks,
Andy

**Comment by Rinsen** [comment]
Hi!

Static files from SD card is supported, they are streamed so you will not have any size problems. I have done benchmarks with large files and it works without any problem. 
You add the static file handler via this line:
webServer.SetFileAndDirectoryService(new FileAndDirectoryService());

And you need to add a directory called WWW to your SD card where you place all static files, this will also work in the emulator but you need a folder on your drive called WWW in local resources folder instead.

I have started building a JSON deserializer but it never made it from prototype state, i could look at how much work remains to get it in a working state, it is a good thing to have! But right now you will only have GET/POST support with forms key/value pairs as in the examples. This will work from both from query string and POST data.

It is also possible to get the data stream and deserialize it in another way in your Controllers and this is located in HttpContext.Socket. But this will only work one time and only if you don´t call the build in handlers as it is from the Socket directly with no server buffers in between.

But i can check the state of my json deserializer and get back here as it will give you the easiest solution.

And i would love to see some code, Angular is awesome! :) 

/Fredrik

**Comment by aallman** [comment]
Thanks for the quick reply.

I wonder if a library like json.net would work to deserialize the posts.  Not sure if it has dependencies that would keep it from running on the micro framework.  In the meantime, I think I can get data to the device using the forms data query screen, but I was hoping to not need to reload the page on each update.

Have you had a chance to look into D3 (http://d3js.org/)?  Since all the work is being done on the client, I think your web server on the netduino could host some pretty interesting visualizations.  AngularJS data-binding to SVGs has gotten a lot better, so for some visualizations, D3 isn’t necessary (though still very helpful!).

Thanks,
Andy

**Comment by Rinsen** [comment]
Hi!

You will absolutely not need to reload the whole page, you can collect data via GET or POST via Angular data service and send any parameters you need, if you need any, in the query string or as form data, and then return these as json data from the Controller. The deserialization is only needed if you have to post in json data objects for some reason but this can be avoided in most cases. 

There is probably no way that json.net will work on NETMF. The metadata support is a bit limited in NETMF and a lot of the dependencies is probably not there. But if you only need to return json data which is what i think you want my serializer should be good enough.

I have not worked with D3 but i have seen some things done in i and they look great so i think that is a good choice. We also looked at Highcharts and i think that it was easier to get started and make charts in that but there may have been a license price tag on that one.

This web server also have support for CORS if you would like to get data from multiple devices and show them at the same time in one browser from one "head"-device. CORS will avoid XSS problems.
http://en.wikipedia.org/wiki/Cross-origin_resource_sharing

I have made a example for this but don´t know where that one is right now and i don´t have any documentation on my implementation more than that you call a method in your Controller called AllowCors() and then it will add the required header and all the other details of how it works is in the wikipedia page :) But it is a pretty basic implementation that only makes it work and does not fully support the standard. 

/Fredrik
