### ISSUE TITLE
Is there any option to stream data

### ISSUE THREAD

**Issue by tomkuijsten** [Rinsen/WebServer#8]
I know that the FileAndDirectoryService can stream files, but I want to stream "normal" controller data as well. I don't have an SD card, but do have some large html strings.

**Comment by Rinsen** [comment]
There is now a way to interrupt the built in execution with Response.IsSent property, and you can look at the ResponseHeaderBuilder and see if that can help you with creating you're response headers so you don´t have to hard code this manually

And i think that you already have found the socket in the HttpContext. And if not, there it is!

**Comment by tomkuijsten** [comment]
Thanks
