### ISSUE TITLE
Crash without any breaks

### ISSUE THREAD

**Issue by tomkuijsten** [Rinsen/WebServer#9]
I have written a program for my netduino 2 plus. I use your webserver to host a single page with some json data being retrieved every 1/2 a second. On the other hand I have an mass flow instrument (the things we make at www.bronkhorst.com) which is polled a few times a second. Those two processes are completely separate. When I start the netduino and don't open a browser, it works for hours without any problem. When I open a browser it works for a few minutes and then just stops, no breakpoints being hit, no logging, nothing, the whole thing just dies. If I press pause in VS, all threads are stopped.

I'm trying to figure out what the problem is. I already traced the memory and that doesn't seem the be the problem. Do you have any clue how I can debug/profile what's going wrong?

**Comment by Rinsen** [comment]
I am pretty sure that this is related to bugs in the network stack, i have had such problems to and have made a dirty work around with a watchdog that reset the Netduino every time it happens and i also have had a periodic power cut, but this is a really ugly solution....

I think that this is a known problem by the Netduino team because of there new TCP/IP network stack.
http://forums.netduino.com/index.php?/forum/29-netduinoip-technical-preview/

When/if this is released I will move this implementation to that version!

**Comment by Rinsen** [comment]
And added to that also the Microsoft team seems to be doing things with the network stack and stability.

"On the functional side, this release includes the reworked network stack integration that improves the stability of the connections."
http://blogs.msdn.com/b/netmfteam/archive/2015/03/09/netmf-4-4-beta-out-on-github.aspx

They have also another great performance enhancement in this release: "In addition, there are improvements in the debugging and deployment functionality and stability.  For example, single stepping and updating the Watch window now takes a fraction of the previous time."

**Comment by tomkuijsten** [comment]
Thanks for the pointers. I try to avoid the watchdog solution, cause I hate it when I can't fix things "the right way". But this might be one of those exceptional cases where I just don't have any other option.

Before using your webserver I created a very simple one for myself, which had the same problem. An error in the network stack could explain those problems as well. Anyway, thanks again for all the quick reply's. I start implementing the watchdog for now and hope that 4.4 will be released soon (or ill switch to win10 on the rpi2 :) ).

**Comment by Sukasa** [comment]
I have noticed this as well, primarily when too many requests come in in too short a time.  It's not great, but you may be able to reduce your poll rate as a temporary fix.

**Comment by tomkuijsten** [comment]
That's actually another problem I got a few times. When too many requests come, I got an IndexOutOfRange Exception, was something with the header I think.

The current problem occurs no matter what polling time I'm using.

**Comment by Rinsen** [comment]
I agree about the watchdog, but I have not found any solid solutions unfortunately.

 Where more exactly did you tomkuijsten get the IndexOutOfRangeException? If it is in my code it could be fixable maybe.

And i already have an rpi2 on my desk waiting for win10 :) That will probably be really really god! I have done some testing with the rpi and Python but it is not as nice to work with as .Net :)

**Comment by tomkuijsten** [comment]
I tried to reproduce it (IndexOutOfRange) today, but I couldn't. Might already be fixed? It was trying to index a header or something in the header string, but that was empty.

Im curious about the win10 version for rpi2, I'm afriad it will only support C++, that would be a bummer for me.

**Comment by Rinsen** [comment]
I have done som smaller changes but it shoulden affect that as far as i know. But you can get back if you get more problems with it.

There is no way that it will only support C++ and not dot net, they are releasing dotnetcore(C#) with Entity Framework and MVC for Linux and Mac now so no, they will not miss there own platform for iot, that would be so stupid so it will never happen :) And if it does we can run the Linux version anyway...

**Comment by tomkuijsten** [comment]
I hope you are right in this matter :) One last thing, do you have a good implementation for a watchdog on the netduino plus 2?

**Comment by Rinsen** [comment]
Me to ;-)

I think it was this one i used for my design, and it is very simple. 

http://www.codeproject.com/Articles/795846/A-Simple-Watchdog-for-the-Netduino

**Comment by Rinsen** [comment]
And make sure that you dont run any other heavy things in that thread!
